theme: minima
minima:
  skin: auto
  nav_pages:
    - index.md
    - indie-archive.md
    - resources.md
title: PHGameStudio
description: PH Game Studio
url: "https://phgamestudio.github.io"
exclude:
  - README.md
  - GEMINI.md
  - _site/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - .bundle/
  - Gemfile.lock
kramdown:
  math_engine: mathjax
