theme: practical-club-website-template
title: PHGameStudio
description: PH Game Studio
url: "https://phgamestudio.github.io"

minima:
  skin: auto
  nav_pages:
    - index.md
    - indie-archive.md
    - resources.md

plugins:
  - jekyll-seo-tag
  - jekyll-feed

kramdown:
  math_engine: mathjax
  input: GFM

exclude:
  - README.md
  - GEMINI.md
  - _site/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - .bundle/
  - Gemfile.lock